---
- hosts: all
  become: true
  gather_facts: false
  roles:
  - { role: ansible }

- hosts: all
  become: true
  roles:
  - { role: server-basic }
  - { role: server-kube, when: "'kube' in roles", tags: ['kube'] }
