---
- hosts: all
  become: true
  gather_facts: false
  roles:
  - { role: ansible }

- hosts: all
  become: true
  roles:
  - { role: server-basic }
  - { role: server-bird,    when: "'bird' in roles",    tags: ['bird'] }
  - { role: server-haproxy, when: "'haproxy' in roles", tags: ['haproxy'] }
  - { role: server-kube,    when: "'kube' in roles",    tags: ['kube'] }
