---
- name: Basic | Backup original config
  import_role:
    name: backup
  vars:
    files:
    - /etc/pacman.conf
    - /etc/pacman.d/mirrorlist
- name: Basic | Create config
  block:
  - template:
      src: pacman.conf.j2
      dest: /etc/pacman.conf
  - template:
      src: section.conf.j2
      dest: /etc/pacman.d/mirrorlist
    vars:
      data: "{{ mirrorlist }}"
- name: Basic | Install packages
  block:
  - set_fact: packages="{{ packages | default({}) | combine(lookup('vars', item)) }}"
    loop: "{{ hostvars[inventory_hostname].keys() | select('match', '^packages_.*$') | list }}"
  - set_fact: packages_present="{{ packages_present | default([]) + [ item.key ] }}"
    loop: "{{ packages | dict2items }}"
    when: not item.value or item.value.state == 'present'
  - set_fact: packages_absent="{{ packages_absent | default([]) + [ item.key ] }}"
    loop: "{{ packages | dict2items }}"
    when: item.value and item.value.state == 'absent'
  - pacman:
      name: "{{ packages_present }}"
      state: present
      update_cache: true
  - pacman:
      name: "{{ packages_absent }}"
      state: absent
- name: Basic | Install symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ symlinks_base }}"
- name: Basic | Configure logrotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/{{ item.key }}
  loop: "{{ logrotate | dict2items }}"
