---
- name: HAProxy | Install
  pacman:
    name: haproxy
    state: present
- name: HAProxy | Backup config
  import_role:
    name: backup
  vars:
    files:
    - /etc/haproxy/haproxy.cfg
- name: HAProxy | Configure
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
- name: HAProxy | Enable service
  service:
    name: haproxy
    enabled: true
    state: started
