---
- template:
    src: kubeadm/init.yaml.j2
    dest: /etc/kubernetes/kubeadm.yaml
- command:
    cmd: kubeadm init --config=/etc/kubernetes/kubeadm.yaml --upload-certs
  register: result
  ignore_errors: true
